import java.io.File;
import java.io.FileNotFoundException;
import java.util.*;

/**
 * This program produces randomly generated strings that resemble pretentious modern art names. All are in the format of
 * "The adjective noun of noun" with the adjectives and nouns being generated by methods. Each of these methods takes a 
 * parameter specifying the text file, these can be changed to any desired file, but the program is built to process files 
 * with one word on each line.
 * 
 * NOTE: if the text files are changed, the global variables for the number of words in each file will need to be changed 
 * as well to the number of words in the files to avoid an array out of bounds error.
 * 
 * @author Adina Friedman
 */
public class RandomGenerator {

	public static final int NUMBER_OF_ADJECTIVES = 1895;
	public static final int NUMBER_OF_NOUNS = 4554;
	public static String[] adjectives = new String[NUMBER_OF_ADJECTIVES];
	public static String[] nouns = new String[NUMBER_OF_NOUNS];

	public static void main(String[] args) throws FileNotFoundException {
		// TODO Auto-generated method stub
		readInAdjectives("Adjectives.txt");
		readInNouns("Nouns.txt");
		String adjective = generateAdjective();
		String firstNoun = generateNoun();
		String secondNoun = generateNoun();
		if(secondNoun == firstNoun) {
			secondNoun = generateNoun();
		} else {
			String artName = "The " + adjective + " " + firstNoun + " of " + secondNoun;
			System.out.println(artName);
		}
	}

	
	public static void readInAdjectives(String fileName)throws FileNotFoundException {
		Scanner adjectiveList = new Scanner(new File(fileName));
		for(int i = 0; i < NUMBER_OF_ADJECTIVES; i++) {
			adjectives[i] = adjectiveList.next();
		}
	}

	//populates the nouns array with the nouns from the file
	public static void readInNouns(String fileName) throws FileNotFoundException {
		Scanner nounList = new Scanner(new File(fileName));
		for(int i = 0; i < NUMBER_OF_NOUNS; i++) {
			nouns[i] = nounList.next();
		}
	}

	//randomly chooses an adjective from the array
	public static String generateAdjective() {
		Random rAdj = new Random();
		String toReturn = adjectives[rAdj.nextInt(NUMBER_OF_ADJECTIVES)],toString;
		return toReturn;
	}

	//randomly chooses a noun from the array
	public static String generateNoun() {
		Random rNoun = new Random();
		String toReturn = nouns[rNoun.nextInt(NUMBER_OF_NOUNS)],toString;
		return toReturn;
	}
}
